//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.UsuarioReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.UsuarioML))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Direccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Colonia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Municipio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Estado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Rol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioReference.ICRUDUsuario")]
    public interface ICRUDUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Add", ReplyAction="http://tempuri.org/ICRUDUsuario/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.UsuarioReference.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        PL_MVC.UsuarioReference.Result Add(ML.UsuarioML Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Add", ReplyAction="http://tempuri.org/ICRUDUsuario/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> AddAsync(ML.UsuarioML Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Update", ReplyAction="http://tempuri.org/ICRUDUsuario/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.UsuarioReference.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        PL_MVC.UsuarioReference.Result Update(ML.UsuarioML Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Update", ReplyAction="http://tempuri.org/ICRUDUsuario/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> UpdateAsync(ML.UsuarioML Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Delete", ReplyAction="http://tempuri.org/ICRUDUsuario/DeleteResponse")]
        PL_MVC.UsuarioReference.Result Delete(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/Delete", ReplyAction="http://tempuri.org/ICRUDUsuario/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> DeleteAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/GetById", ReplyAction="http://tempuri.org/ICRUDUsuario/GetByIdResponse")]
        PL_MVC.UsuarioReference.Result GetById(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/GetById", ReplyAction="http://tempuri.org/ICRUDUsuario/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> GetByIdAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/GetAll", ReplyAction="http://tempuri.org/ICRUDUsuario/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.UsuarioReference.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        PL_MVC.UsuarioReference.Result GetAll(ML.UsuarioML usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDUsuario/GetAll", ReplyAction="http://tempuri.org/ICRUDUsuario/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> GetAllAsync(ML.UsuarioML usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRUDUsuarioChannel : PL_MVC.UsuarioReference.ICRUDUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDUsuarioClient : System.ServiceModel.ClientBase<PL_MVC.UsuarioReference.ICRUDUsuario>, PL_MVC.UsuarioReference.ICRUDUsuario {
        
        public CRUDUsuarioClient() {
        }
        
        public CRUDUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.UsuarioReference.Result Add(ML.UsuarioML Usuario) {
            return base.Channel.Add(Usuario);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> AddAsync(ML.UsuarioML Usuario) {
            return base.Channel.AddAsync(Usuario);
        }
        
        public PL_MVC.UsuarioReference.Result Update(ML.UsuarioML Usuario) {
            return base.Channel.Update(Usuario);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> UpdateAsync(ML.UsuarioML Usuario) {
            return base.Channel.UpdateAsync(Usuario);
        }
        
        public PL_MVC.UsuarioReference.Result Delete(int IdUsuario) {
            return base.Channel.Delete(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> DeleteAsync(int IdUsuario) {
            return base.Channel.DeleteAsync(IdUsuario);
        }
        
        public PL_MVC.UsuarioReference.Result GetById(int IdUsuario) {
            return base.Channel.GetById(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> GetByIdAsync(int IdUsuario) {
            return base.Channel.GetByIdAsync(IdUsuario);
        }
        
        public PL_MVC.UsuarioReference.Result GetAll(ML.UsuarioML usuario) {
            return base.Channel.GetAll(usuario);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.UsuarioReference.Result> GetAllAsync(ML.UsuarioML usuario) {
            return base.Channel.GetAllAsync(usuario);
        }
    }
}
